import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import NavBar from './components/navBar'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className='scroll-smooth'>

      <body className={roboto.className}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
